export const SKIN_PATTERNS = [
  'solid', 'bands', 'stripes', 'gradient', 'rainbow', 'scales', 'spots', 'neon', 'galaxy',
  'diamonds', 'dots', 'camo', 'fire', 'chrome',
] as const;
export const HEAD_SHAPES = ['round', 'viper', 'cute', 'cobra', 'dragon', 'rocket', 'cat'] as const;
export const EYE_STYLES = ['normal', 'angry', 'sleepy', 'cyclops', 'googly'] as const;
export const ACCESSORIES = ['none', 'crown', 'horns', 'hat', 'bow', 'glasses', 'antenna'] as const;
export const BG_PATTERNS = [
  'honeycomb', 'hex', 'grid', 'dots', 'none', 'diamonds', 'triangles', 'circles', 'stars', 'waves', 'bricks', 'scales', 'cross',
] as const;
export const BG_GRADIENTS = ['none', 'radial', 'linear'] as const;
export const PARTICLES = ['none', 'sparkles', 'bubbles', 'snow', 'fireflies', 'embers'] as const;
export const BG_IMAGE_MODES = ['tile', 'cover'] as const;
export const MUSIC_STYLES = ['chill', 'arcade', 'off'] as const;
/** Skins are sent as one byte per snake. */
export const MAX_SKINS = 255;

export type SkinPattern = (typeof SKIN_PATTERNS)[number];
export type HeadShape = (typeof HEAD_SHAPES)[number];
export type BgPattern = (typeof BG_PATTERNS)[number];
export type EyeStyle = (typeof EYE_STYLES)[number];
export type Accessory = (typeof ACCESSORIES)[number];
export type BgGradient = (typeof BG_GRADIENTS)[number];
export type ParticleKind = (typeof PARTICLES)[number];
export type BgImageMode = (typeof BG_IMAGE_MODES)[number];
export type MusicStyle = (typeof MUSIC_STYLES)[number];

export interface SkinDef {
  name: string;
  pattern: SkinPattern;
  head: HeadShape;
  colors: string[];
  glow: boolean;
  enabled: boolean;
  /** Optional extras; older saved skins don't have them. */
  eyes?: EyeStyle;
  eyeColor?: string;
  accessory?: Accessory;
  /** Size of bands, stripes, spots… (1 = default). */
  patternScale?: number;
  /** Strength of the glossy highlight (0–1). */
  shine?: number;
}

export interface Appearance {
  background: string;
  bgPattern: BgPattern;
  patternColor: string;
  patternOpacity: number;
  patternScale: number;
  background2: string;
  bgGradient: BgGradient;
  vignette: number;
  bgImageUrl: string | null;
  bgImageMode: BgImageMode;
  bgImageOpacity: number;
  bgImageScale: number;
  particles: ParticleKind;
  particleColor: string;
  particleDensity: number;
  /** Large, faint colour clouds that give the floor depth (0–1). */
  nebula: number;
  outside: string;
  border: string;
  wallWidth: number;
  wallGlow: number;
  foodGlow: number;
  foodColors: string[];
  landingAccent: string;
  landingAccent2: string;
  landingBackground: string;
  skins: SkinDef[];
}

export interface SoundSettings {
  enabled: boolean;
  musicStyle: MusicStyle;
  musicVolume: number;
  sfxVolume: number;
  /** Legacy single upload; kept so old saved settings keep working. */
  customMusicUrl: string | null;
  /** Uploaded songs, played in order (or shuffled) as background music. */
  tracks: MusicTrack[];
  shuffle: boolean;
}

export interface MusicTrack {
  url: string;
  name: string;
}

/** null = use the value from the server's resource profile. */
export interface GameSettings {
  arenaSize: number | null;
  playersPerRoom: number | null;
  botsPerRoom: number | null;
  foodPerRoom: number | null;
  speed: number;
  boostSpeed: number;
  boostCost: number;
  startMass: number;
  spawnProtectionSec: number;
  /** Multiplier for the length gained from food. */
  growth: number;
}

export interface AdSettings {
  enabled: boolean;
  /** Offer "watch an ad to revive" on the death screen. */
  reviveEnabled: boolean;
  /** Ad shown while the revive countdown runs. */
  reviveCode: string;
  reviveSeconds: number;
  /** Percentage of the length kept when reviving. */
  revivePercent: number;
  /** Revives allowed per game (resets when the player starts a new game). */
  reviveMax: number;
  /** Estimated earnings per 1000 ad impressions, used until real revenue is entered. */
  estimatedCpm: number;
  currency: string;
  /** Ad shown before a game starts (skippable), every N games. */
  playCode: string;
  playEvery: number;
  playSkipSeconds: number;
  /** Extra files served from the site root, e.g. Monetag's sw.js for push ads. */
  rootFiles: RootFile[];
  /** Monetag zone ID for Telegram Mini Apps (rewarded interstitial SDK). */
  tgZone: string;
  /** Require Monetag's server postback before granting a Telegram revive. */
  tgVerify: boolean;
  /** Don't show the web ad codes inside Telegram (use only the Telegram SDK there). */
  tgHideWebAds: boolean;
  /** Secret that must be present in the Monetag postback URL. Generated by the server. */
  postbackSecret: string;
  /** If the rewarded interstitial can't load, try Monetag's rewarded popup before giving up. */
  tgPopupFallback: boolean;
  /** Monetag In-App Interstitial: automatic ads while the Mini App is open. */
  tgInApp: boolean;
  tgInAppFrequency: number;
  tgInAppCapping: number;
  tgInAppInterval: number;
  tgInAppTimeout: number;
  tgInAppEveryPage: boolean;
  /** Rewarded interstitial before games inside Telegram (every `playEvery` games). */
  tgPreroll: boolean;
  /** <meta name="…" content="…"> tags for site verification (Monetag, Google…); always added to <head>. */
  verifyTags: string;
  headCode: string;
  landingCode: string;
  deathCode: string;
  deathEvery: number;
  adsTxt: string;
}

export interface RootFile {
  name: string;
  content: string;
}

export interface GeneralSettings {
  timeZone: string;
}

export interface AllSettings {
  appearance: Appearance;
  sound: SoundSettings;
  game: GameSettings;
  ads: AdSettings;
  general: GeneralSettings;
}

export type SettingsSection = keyof AllSettings;

export const DEFAULT_SKINS: SkinDef[] = [
  { name: 'Mint', pattern: 'solid', head: 'round', colors: ['#4ecdc4'], glow: false, enabled: true },
  { name: 'Coral', pattern: 'bands', head: 'round', colors: ['#e8343b', '#151515', '#ffd23f', '#151515'], glow: false, enabled: true },
  { name: 'Python', pattern: 'scales', head: 'viper', colors: ['#c9a227', '#4a300c', '#e3c25a'], glow: false, enabled: true },
  { name: 'Green Viper', pattern: 'scales', head: 'viper', colors: ['#43b047', '#14451a', '#9be29e'], glow: false, enabled: true },
  { name: 'Neon Pink', pattern: 'neon', head: 'round', colors: ['#ff2fd6'], glow: true, enabled: true },
  { name: 'Neon Cyan', pattern: 'neon', head: 'round', colors: ['#00e5ff'], glow: true, enabled: true },
  { name: 'Rainbow', pattern: 'rainbow', head: 'cute', colors: ['#ff0000'], glow: true, enabled: true },
  { name: 'Tiger', pattern: 'stripes', head: 'viper', colors: ['#ff8c1a', '#1a1a1a'], glow: false, enabled: true },
  { name: 'Galaxy', pattern: 'galaxy', head: 'round', colors: ['#2b1055', '#7597de', '#ffffff'], glow: true, enabled: true },
  { name: 'Lava', pattern: 'gradient', head: 'viper', colors: ['#ffeb3b', '#ff5722', '#b71c1c'], glow: true, enabled: true },
  { name: 'Ice', pattern: 'gradient', head: 'cute', colors: ['#e0f7ff', '#4fc3f7', '#1565c0'], glow: true, enabled: true },
  { name: 'Leopard', pattern: 'spots', head: 'round', colors: ['#f4c542', '#5a3a0a'], glow: false, enabled: true },
  { name: 'Zebra', pattern: 'stripes', head: 'cute', colors: ['#f5f5f5', '#222222'], glow: false, enabled: true },
  { name: 'Gold', pattern: 'solid', head: 'viper', colors: ['#ffc928'], glow: true, enabled: true },
  { name: 'Toxic', pattern: 'spots', head: 'cute', colors: ['#a6ff00', '#2e7d32'], glow: true, enabled: true },
  { name: 'Royal', pattern: 'bands', head: 'round', colors: ['#7b1fa2', '#ffd54f'], glow: false, enabled: true, accessory: 'crown' },
  { name: 'Rattler', pattern: 'diamonds', head: 'viper', colors: ['#b08850', '#4a3420', '#e8d3a8'], glow: false, enabled: true, eyes: 'angry' },
  { name: 'King Cobra', pattern: 'bands', head: 'cobra', colors: ['#2d2a26', '#d9c27a'], glow: false, enabled: true, eyes: 'angry', patternScale: 0.7 },
  { name: 'Dragon', pattern: 'scales', head: 'dragon', colors: ['#c62828', '#4a0d0d', '#ff8a65'], glow: true, enabled: true, eyes: 'angry', eyeColor: '#ffb300' },
  { name: 'Phoenix', pattern: 'fire', head: 'dragon', colors: ['#fff176', '#ff7043', '#c62828'], glow: true, enabled: true },
  { name: 'Chrome', pattern: 'chrome', head: 'round', colors: ['#9fb3c8'], glow: false, enabled: true, accessory: 'glasses', shine: 1 },
  { name: 'Jungle', pattern: 'camo', head: 'viper', colors: ['#556b2f', '#2e3b1f', '#8f9b5a', '#1d2614'], glow: false, enabled: true },
  { name: 'Bubblegum', pattern: 'dots', head: 'cute', colors: ['#ff8fc7', '#ffffff'], glow: false, enabled: true, accessory: 'bow', eyes: 'googly' },
  { name: 'Alien', pattern: 'gradient', head: 'round', colors: ['#7cff6b', '#00b894'], glow: true, enabled: true, eyes: 'cyclops', accessory: 'antenna' },
  { name: 'Devil', pattern: 'solid', head: 'viper', colors: ['#d50000'], glow: true, enabled: true, accessory: 'horns', eyes: 'angry', eyeColor: '#ffea00' },
  { name: 'Cosmic Dragon', pattern: 'galaxy', head: 'dragon', colors: ['#16307a', '#3fa7ff', '#ffffff'], glow: true, enabled: true, eyes: 'angry', eyeColor: '#7df9ff', shine: 0.8 },
  { name: 'Rocket', pattern: 'bands', head: 'rocket', colors: ['#f2f4f8', '#e53935', '#f2f4f8', '#9aa4b5'], glow: false, enabled: true, patternScale: 1.4, shine: 0.9 },
  { name: 'Void', pattern: 'stripes', head: 'viper', colors: ['#15151f', '#19e6c9'], glow: true, enabled: true, eyes: 'angry', eyeColor: '#19e6c9', patternScale: 0.8 },
  { name: 'Space Cat', pattern: 'stripes', head: 'cat', colors: ['#ff8fc7', '#ffc2e0'], glow: false, enabled: true, eyes: 'normal', eyeColor: '#7c4dff', patternScale: 1.2 },
  { name: 'Gentleman', pattern: 'stripes', head: 'round', colors: ['#37474f', '#90a4ae'], glow: false, enabled: true, accessory: 'hat', eyes: 'sleepy' },
];

export const DEFAULT_SETTINGS: AllSettings = {
  appearance: {
    background: '#151c2e',
    bgPattern: 'honeycomb',
    patternColor: '#8fa8ff',
    patternOpacity: 0.12,
    patternScale: 1,
    background2: '#05070f',
    bgGradient: 'radial',
    vignette: 0.4,
    bgImageUrl: null,
    bgImageMode: 'tile',
    bgImageOpacity: 0.6,
    bgImageScale: 1,
    particles: 'sparkles',
    particleColor: '#9fb4ff',
    particleDensity: 0.3,
    nebula: 0.5,
    outside: '#06070d',
    border: '#3fe0ff',
    wallWidth: 8,
    wallGlow: 0.8,
    foodGlow: 0.8,
    foodColors: ['#ff5d73', '#4ecdc4', '#ffd166', '#8c7bff', '#5ee06a', '#ff8c42', '#3fa7ff', '#f15bb5'],
    landingAccent: '#4ecdc4',
    landingAccent2: '#5ee06a',
    landingBackground: '#0b1020',
    skins: DEFAULT_SKINS,
  },
  sound: {
    enabled: true,
    musicStyle: 'chill',
    musicVolume: 0.35,
    sfxVolume: 0.6,
    customMusicUrl: null,
    tracks: [],
    shuffle: true,
  },
  game: {
    arenaSize: null,
    playersPerRoom: null,
    botsPerRoom: null,
    foodPerRoom: null,
    speed: 165,
    boostSpeed: 330,
    boostCost: 7,
    startMass: 10,
    spawnProtectionSec: 2.5,
    growth: 2,
  },
  ads: {
    enabled: false,
    reviveEnabled: true,
    reviveCode: '',
    reviveSeconds: 15,
    revivePercent: 60,
    reviveMax: 1,
    estimatedCpm: 1.5,
    currency: 'USD',
    playCode: '',
    playEvery: 3,
    playSkipSeconds: 5,
    rootFiles: [],
    tgZone: '11979693',
    tgVerify: false,
    tgHideWebAds: true,
    postbackSecret: '',
    tgPopupFallback: true,
    tgInApp: true,
    tgInAppFrequency: 2,
    tgInAppCapping: 0.1,
    tgInAppInterval: 30,
    tgInAppTimeout: 5,
    tgInAppEveryPage: false,
    tgPreroll: false,
    verifyTags: '',
    headCode: '',
    landingCode: '',
    deathCode: '',
    deathEvery: 2,
    adsTxt: '',
  },
  general: {
    timeZone: 'UTC',
  },
};

/** What the public pages and the game client receive. */
export interface PublicConfig {
  appearance: Omit<Appearance, 'landingAccent' | 'landingAccent2' | 'landingBackground'>;
  sound: SoundSettings;
  ads: {
    enabled: boolean;
    deathCode: string;
    deathEvery: number;
    reviveEnabled: boolean;
    reviveCode: string;
    reviveSeconds: number;
    revivePercent: number;
    playCode: string;
    playEvery: number;
    playSkipSeconds: number;
    tgZone: string;
    tgHideWebAds: boolean;
    tgPopupFallback: boolean;
    tgPreroll: boolean;
    tgInApp: null | { frequency: number; capping: number; interval: number; timeout: number; everyPage: boolean };
  };
}

const META_TAG = /<meta\s+(?:name|property)\s*=\s*["']([A-Za-z0-9_.:-]{1,64})["']\s+content\s*=\s*["']([^"'<>]{1,512})["']\s*\/?>/gi;

/** Keeps only <meta name="…" content="…"> tags and rebuilds them so nothing else can be injected. */
export function sanitizeMetaTags(input: string): string {
  const escape = (s: string) => s.replace(/&/g, '&amp;').replace(/"/g, '&quot;');
  const out: string[] = [];
  for (const m of input.matchAll(META_TAG)) out.push(`<meta name="${escape(m[1])}" content="${escape(m[2])}">`);
  return out.slice(0, 20).join('');
}

export function toPublicConfig(s: AllSettings): PublicConfig {
  const { landingAccent: _a, landingAccent2: _b, landingBackground: _c, ...appearance } = s.appearance;
  return {
    appearance,
    sound: s.sound,
    ads: {
      enabled: s.ads.enabled,
      deathCode: s.ads.enabled ? s.ads.deathCode : '',
      deathEvery: s.ads.deathEvery,
      reviveEnabled: s.ads.reviveEnabled,
      reviveCode: s.ads.enabled ? s.ads.reviveCode : '',
      reviveSeconds: s.ads.reviveSeconds,
      revivePercent: s.ads.revivePercent,
      playCode: s.ads.enabled ? s.ads.playCode : '',
      playEvery: s.ads.playEvery,
      playSkipSeconds: s.ads.playSkipSeconds,
      // Telegram ads are switched on by having a zone ID, independently of the web ads switch.
      tgZone: s.ads.tgZone,
      tgHideWebAds: s.ads.tgHideWebAds,
      tgPopupFallback: s.ads.tgPopupFallback,
      tgPreroll: s.ads.tgPreroll,
      tgInApp: s.ads.tgInApp
        ? {
            frequency: s.ads.tgInAppFrequency,
            capping: s.ads.tgInAppCapping,
            interval: s.ads.tgInAppInterval,
            timeout: s.ads.tgInAppTimeout,
            everyPage: s.ads.tgInAppEveryPage,
          }
        : null,
    },
  };
}
